-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvyqiAZyC5sLM9clG
m/YOznwZnywuWdTPFCSiLsG2Dd+gCgYIKoZIzj0DAQehRANCAATM0onJqCDaLZJz
JJ9iwUurf88t8sbnsoszJWskkFF1Wc1ACP3GmUjaf5C1DdyUWTxvvtPssEt+1Y6Z
tLUrOthA
-----END PRIVATE KEY-----